include: [acpi.sys, battc.sys, bios.vxd,
  cbss.vxd, cmbatt.sys, compbatt.sys,
  debugcmd.vxd, dibeng.dll, ec.sys, eisa.vxd,
  gdi32.dll, gdi.exe, hid.dll, ircomm.vxd,
  irenum.vxd, irlamp.vxd, irlapfrm.vxd,
  isapnp.vxd, joyhid.vxd, kbdhid.vxd,
  kernel32.dll, krnl386.exe, ksclockf.ax,
  ksdata.ax, ksinterf.ax, ksproxy.ax,
  ksuser.dll, ksvpintf.ax, lptenum.vxd,
  mapi32.dll, midimap.drv, mmci.dll,
  mmdevldr.vxd, mmhid.dll, mmsound.drv,
  mmsystem.dll, mouhid.vxd, msacm32.dll,
  msacm.dll, msvfw32.dll, msvideo.dll,
  ndis.vxd, ndiswan.vxd, netdidbg.dll,
  pccard.vxd, pci.vxd, pkpd32.dll, pkpd.dll,
  pppmac.vxd, serenum.vxd, socketsv.vxd,
  spoolss.dll, sysdm.cpl, tapi.dll, unidrv.dll,
  unimodem.vxd, user32.dll, user.exe,
  vdhcp.386, vfwwdm.drv, vip.386, vjoyd.vxd,
  vnbt.386, vtcp.386, vtdi.386, vudp.386,
  wan.tsp, wdmaud.drv, winmm.dll, configmg.vxd,
  ifsmgr.vxd, ios.vxd, ntkern.vxd,
  udf.vxd, vcd.vxd, vcomm.vxd,
  vdd.vxd, vdmad.vxd, vfat.vxd,
  vflatd.vxd, vkd.vxd, vmm.vxd,
  vmouse.vxd, vpd.vxd, vpicd.vxd,
  vwin32.vxd, vxdldr.vxd, cdfs.vxd,
  cdtsd.vxd, cdvsd.vxd, disktsd.vxd,
  diskvsd.vxd, rmm.pdr, scsiport.pdr,
  voltrack.vxd, 1394bus.sys, hidclass.sys,
  ohci1394.sys, openhci.sys, uhcd.sys,
  usbaudio.sys, usbd.sys, usbhub.sys,
  usbscan.sys, vfwwdm32.dll, wdmaud.sys,
  wmidrv.sys]
versions:
- Windows 98 Debug
- Windows 98 Retail
- Windows 98SE Debug
- Windows 98SE Retail
- Windows 95