include: [
  acpi.sys,
  battc.sys,
  bios.vxd,
  cbss.vxd,
  cmbatt.sys,
  compbatt.sys,
  debugcmd.vxd,
  dibeng.dll,
  ec.sys,
  eisa.vxd,
  gdi32.dll,
  gdi.exe,
  hid.dll,
  ircomm.vxd,
  irenum.vxd,
  irlamp.vxd,
  irlapfrm.vxd,
  isapnp.vxd,
  joyhid.vxd,
  kbdhid.vxd,
  kernel32.dll,
  krnl386.exe,
  ksclockf.ax,
  ksdata.ax,
  ksinterf.ax,
  ksproxy.ax,
  ksuser.dll,
  ksvpintf.ax,
  lptenum.vxd,
  mapi32.dll,
  midimap.drv,
  mmci.dll,
  mmdevldr.vxd,
  mmhid.dll,
  mmsound.drv,
  mmsystem.dll,
  mouhid.vxd,
  msacm32.dll,
  msacm.dll,
  msvfw32.dll,
  msvideo.dll,
  ndis.vxd,
  ndiswan.vxd,
  netdidbg.dll,
  pccard.vxd,
  pci.vxd,
  pkpd32.dll,
  pkpd.dll,
  pppmac.vxd,
  serenum.vxd,
  socketsv.vxd,
  spoolss.dll,
  sysdm.cpl,
  tapi.dll,
  unidrv.dll,
  unimodem.vxd,
  user32.dll,
  user.exe,
  vdhcp.386,
  vfwwdm.drv,
  vip.386,
  vjoyd.vxd,
  vnbt.386,
  vtcp.386,
  vtdi.386,
  vudp.386,
  wan.tsp,
  wdmaud.drv,
  winmm.dll,
  vmm32/configmg.vxd,
  vmm32/ifsmgr.vxd,
  vmm32/ios.vxd,
  vmm32/ntkern.vxd,
  vmm32/udf.vxd,
  vmm32/vcd.vxd,
  vmm32/vcomm.vxd,
  vmm32/vdd.vxd,
  vmm32/vdmad.vxd,
  vmm32/vfat.vxd,
  vmm32/vflatd.vxd,
  vmm32/vkd.vxd,
  vmm32/vmm.vxd,
  vmm32/vmouse.vxd,
  vmm32/vpd.vxd,
  vmm32/vpicd.vxd,
  vmm32/vwin32.vxd,
  vmm32/vxdldr.vxd,
  iosubsys/cdfs.vxd,
  iosubsys/cdtsd.vxd,
  iosubsys/cdvsd.vxd,
  iosubsys/disktsd.vxd,
  iosubsys/diskvsd.vxd,
  iosubsys/rmm.pdr,
  iosubsys/scsiport.pdr,
  iosubsys/voltrack.vxd
]

