include: [windows/system/acpi.sys, windows/system/battc.sys, windows/system/bios.vxd,
  windows/system/cbss.vxd, windows/system/cmbatt.sys, windows/system/compbatt.sys,
  windows/system/debugcmd.vxd, windows/system/dibeng.dll, windows/system/ec.sys, windows/system/eisa.vxd,
  windows/system/gdi32.dll, windows/system/gdi.exe, windows/system/hid.dll, windows/system/ircomm.vxd,
  windows/system/irenum.vxd, windows/system/irlamp.vxd, windows/system/irlapfrm.vxd,
  windows/system/isapnp.vxd, windows/system/joyhid.vxd, windows/system/kbdhid.vxd,
  windows/system/kernel32.dll, windows/system/krnl386.exe, windows/system/ksclockf.ax,
  windows/system/ksdata.ax, windows/system/ksinterf.ax, windows/system/ksproxy.ax,
  windows/system/ksuser.dll, windows/system/ksvpintf.ax, windows/system/lptenum.vxd,
  windows/system/mapi32.dll, windows/system/midimap.drv, windows/system/mmci.dll,
  windows/system/mmdevldr.vxd, windows/system/mmhid.dll, windows/system/mmsound.drv,
  windows/system/mmsystem.dll, windows/system/mouhid.vxd, windows/system/msacm32.dll,
  windows/system/msacm.dll, windows/system/msvfw32.dll, windows/system/msvideo.dll,
  windows/system/ndis.vxd, windows/system/ndiswan.vxd, windows/system/netdidbg.dll,
  windows/system/pccard.vxd, windows/system/pci.vxd, windows/system/pkpd32.dll, windows/system/pkpd.dll,
  windows/system/pppmac.vxd, windows/system/serenum.vxd, windows/system/socketsv.vxd,
  windows/system/spoolss.dll, windows/system/sysdm.cpl, windows/system/tapi.dll, windows/system/unidrv.dll,
  windows/system/unimodem.vxd, windows/system/user32.dll, windows/system/user.exe,
  windows/system/vdhcp.386, windows/system/vfwwdm.drv, windows/system/vip.386, windows/system/vjoyd.vxd,
  windows/system/vnbt.386, windows/system/vtcp.386, windows/system/vtdi.386, windows/system/vudp.386,
  windows/system/wan.tsp, windows/system/wdmaud.drv, windows/system/winmm.dll, windows/system/vmm32/configmg.vxd,
  windows/system/vmm32/ifsmgr.vxd, windows/system/vmm32/ios.vxd, windows/system/vmm32/ntkern.vxd,
  windows/system/vmm32/udf.vxd, windows/system/vmm32/vcd.vxd, windows/system/vmm32/vcomm.vxd,
  windows/system/vmm32/vdd.vxd, windows/system/vmm32/vdmad.vxd, windows/system/vmm32/vfat.vxd,
  windows/system/vmm32/vflatd.vxd, windows/system/vmm32/vkd.vxd, windows/system/vmm32/vmm.vxd,
  windows/system/vmm32/vmouse.vxd, windows/system/vmm32/vpd.vxd, windows/system/vmm32/vpicd.vxd,
  windows/system/vmm32/vwin32.vxd, windows/system/vmm32/vxdldr.vxd, windows/system/iosubsys/cdfs.vxd,
  windows/system/iosubsys/cdtsd.vxd, windows/system/iosubsys/cdvsd.vxd, windows/system/iosubsys/disktsd.vxd,
  windows/system/iosubsys/diskvsd.vxd, windows/system/iosubsys/rmm.pdr, windows/system/iosubsys/scsiport.pdr,
  windows/system/iosubsys/voltrack.vxd, windows/system32/drivers/1394bus.sys, windows/system32/drivers/hidclass.sys,
  windows/system32/drivers/ohci1394.sys, windows/system32/drivers/openhci.sys, windows/system32/drivers/uhcd.sys,
  windows/system32/drivers/usbaudio.sys, windows/system32/drivers/usbd.sys, windows/system32/drivers/usbhub.sys,
  windows/system32/drivers/usbscan.sys, windows/system32/drivers/vfwwdm32.dll, windows/system32/drivers/wdmaud.sys,
  windows/system32/drivers/wmidrv.sys]
versions:
- Windows 98 Debug
- Windows 98 Retail
